version: '3.8'

services:
  api:
    build:
      context: ./nodejs-api
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_DB: ecommerce
    depends_on:
      - mydb


  angular:
    build:
      context: ./ecommerce
      dockerfile: Dockerfile
    ports:
      - 4200:80
    depends_on:
      - api


  mydb:
    image: mariadb:lts
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: ecommerce
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d


volumes:
  db-data:
