services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecommerce
    volumes:
      - my_vol:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
  api:
    build: ./nodejs-api
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: ecommerce

volumes:
  my_vol:
