# Angular build stage
FROM node:18 AS build
WORKDIR /app
COPY package*.json ./
# Clean node_modules and reinstall
RUN rm -rf node_modules && npm install

COPY . .
RUN npm run build --prod

# Nginx stage
FROM nginx:alpine
COPY --from=build /app/dist/ /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
